FROM python:3.12.0-slim

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

# install python dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the local src directory to the working directory
COPY . .

# running migrations
RUN python manage.py makemigrations
RUN python manage.py migrate

# initialize the database
RUN python manage.py init_permissions
RUN python manage.py init_tickets

# create a superuser
RUN python manage.py createsuperuser --username admin --email admin@example.com --noinput

# create a simple user
RUN python manage.py createuser --username=user --email=user@example.com --password=user

# create an api key for the superuser
RUN python manage.py apikey --action=create --user=admin --application=default

# create an api key for the simple user
RUN python manage.py apikey --action=create --user=user --application=default

# gunicorn
#CMD ["gunicorn", "--config", "gunicorn-cfg.py", "core.wsgi"]

# Specify the command to run on container start
CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]