from django.urls import path
from . import views

urlpatterns = [
    path('', views.app_index, name='app_index'),
    path('ticket/', views.index, name='index'),
    path('ticket/pull/', views.pull_request, name='pull_request'),
    path('ticket/statistics/', views.statistics_view, name='statistics'),
    path('ticket/in_progress', views.in_progress_view, name='in_progress'),
    path("help/", views.help_view, name="view_help"),
    path('ticket/issues/', views.list_issues, name='list_issues'),
    path('ticket/changes/', views.view_changes, name='view_changes'),
    path("ticket/my/", views.my_tasks, name="my_tasks"),
    path('ticket/search/', views.search_tickets, name='search_tickets'),
    path('ticket/<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    path('ticket/new/', views.new_ticket, name='new_ticket'),
    path('ticket/closed/', views.list_closed_tickets, name='list_closed_tickets'),
    path('ticket/hidden/', views.list_hidden_tickets, name='list_hidden_tickets'),
    path('ticket/<int:ticket_id>/edit/', views.edit_ticket, name='edit_ticket'),
    path('ticket/<int:ticket_id>/hide/', views.hide_ticket, name='hide_ticket'),
    path('ticket/<int:ticket_id>/unhide/', views.unhide_ticket, name='unhide_ticket'),
    path('ticket/<int:ticket_id>/comment/', views.new_comment, name='new_comment'),
    path('ticket/<int:ticket_id>/comment/<int:comment_id>/edit/', views.edit_comment, name='edit_comment'),
    path('ticket/<int:ticket_id>/comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('ticket/<int:ticket_id>/upvote/', views.upvote_ticket, name='upvote_ticket'),
    path('ticket/<int:ticket_id>/downvote/', views.downvote_ticket, name='downvote_ticket'),
    path('ticket/<int:ticket_id>/comment/<int:comment_id>/upvote/', views.upvote_comment, name='upvote_comment'),
    path('ticket/<int:ticket_id>/comment/<int:comment_id>/downvote/', views.downvote_comment, name='downvote_comment'),
    # Add api urls
    path('ticket/api/v1/list/', views.api_list_tickets, name='api_ticket_list'),
    path('ticket/api/v1/detail/<int:ticket_id>/', views.api_ticket_detail, name='api_ticket_detail'),
    path('ticket/api/v1/edit/<int:ticket_id>/', views.api_ticket_edit, name='api_ticket_edit'),
    path('ticket/api/v1/create/', views.api_ticket_create, name='api_ticket_create'),
    path('ticket/api/v1/add_comment/<int:ticket_id>/', views.api_add_comment, name='api_ticket_add_comment'),
]
